### ISSUE TITLE
Link "Get started" button to documentation

### ISSUE THREAD

**Issue by astanush** [fourkitchens/emulsify-landingpage#20]
Now that Emulsify uses multiple repos, any single repo is not a good general starting point to link users to.

Two requests:

1. Link the "Get started" button to documentation: https://docs.emulsify.info/
2. Remove the "Documentation" link that appears below it

**Comment by astanush** [comment]
This is semi-urgent, because there is currently a weird redirect happening ([Jira issue](https://fourkitchens.atlassian.net/browse/GS-76))

**Comment by amazingrando** [comment]
This is resolved.
